//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.21 at 04:49:26 PM EST 
//


package com.javatechie.spring.soap.api.getRating;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CommodityInput complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CommodityInput"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CommodityClass" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="CommodityPieces" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="CommodityPieceType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CommodityWeightPerPiece" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="CommodityWeight" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="CommodityLength" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="CommodityWidth" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="CommodityHeight" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="CommodityHazmat" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CommodityInput", propOrder = {
    "commodityClass",
    "commodityPieces",
    "commodityPieceType",
    "commodityWeightPerPiece",
    "commodityWeight",
    "commodityLength",
    "commodityWidth",
    "commodityHeight",
    "commodityHazmat"
})
public class CommodityInput {

    @XmlElement(name = "CommodityClass", required = true)
    protected BigDecimal commodityClass;
    @XmlElement(name = "CommodityPieces")
    protected int commodityPieces;
    @XmlElement(name = "CommodityPieceType")
    protected String commodityPieceType;
    @XmlElement(name = "CommodityWeightPerPiece")
    protected int commodityWeightPerPiece;
    @XmlElement(name = "CommodityWeight")
    protected int commodityWeight;
    @XmlElement(name = "CommodityLength")
    protected int commodityLength;
    @XmlElement(name = "CommodityWidth")
    protected int commodityWidth;
    @XmlElement(name = "CommodityHeight")
    protected int commodityHeight;
    @XmlElement(name = "CommodityHazmat")
    protected String commodityHazmat;

    /**
     * Gets the value of the commodityClass property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCommodityClass() {
        return commodityClass;
    }

    /**
     * Sets the value of the commodityClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCommodityClass(BigDecimal value) {
        this.commodityClass = value;
    }

    /**
     * Gets the value of the commodityPieces property.
     * 
     */
    public int getCommodityPieces() {
        return commodityPieces;
    }

    /**
     * Sets the value of the commodityPieces property.
     * 
     */
    public void setCommodityPieces(int value) {
        this.commodityPieces = value;
    }

    /**
     * Gets the value of the commodityPieceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommodityPieceType() {
        return commodityPieceType;
    }

    /**
     * Sets the value of the commodityPieceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommodityPieceType(String value) {
        this.commodityPieceType = value;
    }

    /**
     * Gets the value of the commodityWeightPerPiece property.
     * 
     */
    public int getCommodityWeightPerPiece() {
        return commodityWeightPerPiece;
    }

    /**
     * Sets the value of the commodityWeightPerPiece property.
     * 
     */
    public void setCommodityWeightPerPiece(int value) {
        this.commodityWeightPerPiece = value;
    }

    /**
     * Gets the value of the commodityWeight property.
     * 
     */
    public int getCommodityWeight() {
        return commodityWeight;
    }

    /**
     * Sets the value of the commodityWeight property.
     * 
     */
    public void setCommodityWeight(int value) {
        this.commodityWeight = value;
    }

    /**
     * Gets the value of the commodityLength property.
     * 
     */
    public int getCommodityLength() {
        return commodityLength;
    }

    /**
     * Sets the value of the commodityLength property.
     * 
     */
    public void setCommodityLength(int value) {
        this.commodityLength = value;
    }

    /**
     * Gets the value of the commodityWidth property.
     * 
     */
    public int getCommodityWidth() {
        return commodityWidth;
    }

    /**
     * Sets the value of the commodityWidth property.
     * 
     */
    public void setCommodityWidth(int value) {
        this.commodityWidth = value;
    }

    /**
     * Gets the value of the commodityHeight property.
     * 
     */
    public int getCommodityHeight() {
        return commodityHeight;
    }

    /**
     * Sets the value of the commodityHeight property.
     * 
     */
    public void setCommodityHeight(int value) {
        this.commodityHeight = value;
    }

    /**
     * Gets the value of the commodityHazmat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommodityHazmat() {
        return commodityHazmat;
    }

    /**
     * Sets the value of the commodityHazmat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommodityHazmat(String value) {
        this.commodityHazmat = value;
    }

}
