//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.21 at 04:49:26 PM EST 
//


package com.javatechie.spring.soap.api.getRating;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="RatingParam" type="{http://tempuri.org/}RatingEngineInput" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ratingParam"
})
@XmlRootElement(name = "GetRating")
public class GetRating {

    @XmlElement(name = "RatingParam")
    protected RatingEngineInput ratingParam;

    /**
     * Gets the value of the ratingParam property.
     * 
     * @return
     *     possible object is
     *     {@link RatingEngineInput }
     *     
     */
    public RatingEngineInput getRatingParam() {
        return ratingParam;
    }

    /**
     * Sets the value of the ratingParam property.
     * 
     * @param value
     *     allowed object is
     *     {@link RatingEngineInput }
     *     
     */
    public void setRatingParam(RatingEngineInput value) {
        this.ratingParam = value;
    }

}
