//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.21 at 04:49:26 PM EST 
//


package com.javatechie.spring.soap.api.getRating;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.javatechie.spring.soap.api.getRating package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.javatechie.spring.soap.api.getRating
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetRating }
     * 
     */
    public GetRating createGetRating() {
        return new GetRating();
    }

    /**
     * Create an instance of {@link RatingEngineInput }
     * 
     */
    public RatingEngineInput createRatingEngineInput() {
        return new RatingEngineInput();
    }

    /**
     * Create an instance of {@link GetRatingResponse }
     * 
     */
    public GetRatingResponse createGetRatingResponse() {
        return new GetRatingResponse();
    }

    /**
     * Create an instance of {@link ArrayOfRatingOutput }
     * 
     */
    public ArrayOfRatingOutput createArrayOfRatingOutput() {
        return new ArrayOfRatingOutput();
    }

    /**
     * Create an instance of {@link RatingInput }
     * 
     */
    public RatingInput createRatingInput() {
        return new RatingInput();
    }

    /**
     * Create an instance of {@link ArrayOfAccessorialInput }
     * 
     */
    public ArrayOfAccessorialInput createArrayOfAccessorialInput() {
        return new ArrayOfAccessorialInput();
    }

    /**
     * Create an instance of {@link AccessorialInput }
     * 
     */
    public AccessorialInput createAccessorialInput() {
        return new AccessorialInput();
    }

    /**
     * Create an instance of {@link ArrayOfCommodityInput }
     * 
     */
    public ArrayOfCommodityInput createArrayOfCommodityInput() {
        return new ArrayOfCommodityInput();
    }

    /**
     * Create an instance of {@link CommodityInput }
     * 
     */
    public CommodityInput createCommodityInput() {
        return new CommodityInput();
    }

    /**
     * Create an instance of {@link RatingOutput }
     * 
     */
    public RatingOutput createRatingOutput() {
        return new RatingOutput();
    }

    /**
     * Create an instance of {@link ArrayOfAccessorialOutput }
     * 
     */
    public ArrayOfAccessorialOutput createArrayOfAccessorialOutput() {
        return new ArrayOfAccessorialOutput();
    }

    /**
     * Create an instance of {@link AccessorialOutput }
     * 
     */
    public AccessorialOutput createAccessorialOutput() {
        return new AccessorialOutput();
    }

}
