//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.21 at 04:49:26 PM EST 
//


package com.javatechie.spring.soap.api.getRating;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RatingEngineInput complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RatingEngineInput"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="RatingInput" type="{http://tempuri.org/}RatingInput" minOccurs="0"/&gt;
 *         &lt;element name="AccessorialInput" type="{http://tempuri.org/}ArrayOfAccessorialInput" minOccurs="0"/&gt;
 *         &lt;element name="CommodityInput" type="{http://tempuri.org/}ArrayOfCommodityInput" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RatingEngineInput", propOrder = {
    "ratingInput",
    "accessorialInput",
    "commodityInput"
})
public class RatingEngineInput {

    @XmlElement(name = "RatingInput")
    protected RatingInput ratingInput;
    @XmlElement(name = "AccessorialInput")
    protected ArrayOfAccessorialInput accessorialInput;
    @XmlElement(name = "CommodityInput")
    protected ArrayOfCommodityInput commodityInput;

    /**
     * Gets the value of the ratingInput property.
     * 
     * @return
     *     possible object is
     *     {@link RatingInput }
     *     
     */
    public RatingInput getRatingInput() {
        return ratingInput;
    }

    /**
     * Sets the value of the ratingInput property.
     * 
     * @param value
     *     allowed object is
     *     {@link RatingInput }
     *     
     */
    public void setRatingInput(RatingInput value) {
        this.ratingInput = value;
    }

    /**
     * Gets the value of the accessorialInput property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfAccessorialInput }
     *     
     */
    public ArrayOfAccessorialInput getAccessorialInput() {
        return accessorialInput;
    }

    /**
     * Sets the value of the accessorialInput property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfAccessorialInput }
     *     
     */
    public void setAccessorialInput(ArrayOfAccessorialInput value) {
        this.accessorialInput = value;
    }

    /**
     * Gets the value of the commodityInput property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfCommodityInput }
     *     
     */
    public ArrayOfCommodityInput getCommodityInput() {
        return commodityInput;
    }

    /**
     * Sets the value of the commodityInput property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfCommodityInput }
     *     
     */
    public void setCommodityInput(ArrayOfCommodityInput value) {
        this.commodityInput = value;
    }

}
