//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.21 at 04:49:26 PM EST 
//


package com.javatechie.spring.soap.api.getRating;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RatingOutput complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RatingOutput"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="RequestID" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="ServiceLevelID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DeliveryDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DeliveryTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="StandardFreightCharge" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="StandardTotalRate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Message" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="AccessorialOutput" type="{http://tempuri.org/}ArrayOfAccessorialOutput" minOccurs="0"/&gt;
 *         &lt;element name="TransitDays" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RatingOutput", propOrder = {
    "requestID",
    "serviceLevelID",
    "deliveryDate",
    "deliveryTime",
    "standardFreightCharge",
    "standardTotalRate",
    "message",
    "accessorialOutput",
    "transitDays"
})
public class RatingOutput {

    @XmlElement(name = "RequestID")
    protected int requestID;
    @XmlElement(name = "ServiceLevelID")
    protected String serviceLevelID;
    @XmlElement(name = "DeliveryDate")
    protected String deliveryDate;
    @XmlElement(name = "DeliveryTime")
    protected String deliveryTime;
    @XmlElement(name = "StandardFreightCharge")
    protected String standardFreightCharge;
    @XmlElement(name = "StandardTotalRate")
    protected String standardTotalRate;
    @XmlElement(name = "Message")
    protected String message;
    @XmlElement(name = "AccessorialOutput")
    protected ArrayOfAccessorialOutput accessorialOutput;
    @XmlElement(name = "TransitDays")
    protected int transitDays;

    /**
     * Gets the value of the requestID property.
     * 
     */
    public int getRequestID() {
        return requestID;
    }

    /**
     * Sets the value of the requestID property.
     * 
     */
    public void setRequestID(int value) {
        this.requestID = value;
    }

    /**
     * Gets the value of the serviceLevelID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceLevelID() {
        return serviceLevelID;
    }

    /**
     * Sets the value of the serviceLevelID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceLevelID(String value) {
        this.serviceLevelID = value;
    }

    /**
     * Gets the value of the deliveryDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryDate() {
        return deliveryDate;
    }

    /**
     * Sets the value of the deliveryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryDate(String value) {
        this.deliveryDate = value;
    }

    /**
     * Gets the value of the deliveryTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryTime() {
        return deliveryTime;
    }

    /**
     * Sets the value of the deliveryTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryTime(String value) {
        this.deliveryTime = value;
    }

    /**
     * Gets the value of the standardFreightCharge property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStandardFreightCharge() {
        return standardFreightCharge;
    }

    /**
     * Sets the value of the standardFreightCharge property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStandardFreightCharge(String value) {
        this.standardFreightCharge = value;
    }

    /**
     * Gets the value of the standardTotalRate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStandardTotalRate() {
        return standardTotalRate;
    }

    /**
     * Sets the value of the standardTotalRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStandardTotalRate(String value) {
        this.standardTotalRate = value;
    }

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessage(String value) {
        this.message = value;
    }

    /**
     * Gets the value of the accessorialOutput property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfAccessorialOutput }
     *     
     */
    public ArrayOfAccessorialOutput getAccessorialOutput() {
        return accessorialOutput;
    }

    /**
     * Sets the value of the accessorialOutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfAccessorialOutput }
     *     
     */
    public void setAccessorialOutput(ArrayOfAccessorialOutput value) {
        this.accessorialOutput = value;
    }

    /**
     * Gets the value of the transitDays property.
     * 
     */
    public int getTransitDays() {
        return transitDays;
    }

    /**
     * Sets the value of the transitDays property.
     * 
     */
    public void setTransitDays(int value) {
        this.transitDays = value;
    }

}
